### ISSUE TITLE
A question of the derivatives

### ISSUE THREAD

**Issue by nlqnly** [weili101/Deep_Plates#2]
Thanks for sharing the codes of the PDE-based PINN. However, I cannot understand why the derivatives need to multiply and divide the model size, like in the code for first order derivatives: du_y, dv_x = du_y*a/b, dv_x*b/a, and for second order derivatives: du_xx, du_yy, du_xy = du_xx/a, du_yy*a/b**2, du_xy/b. We're guessing that these are modifications for implicit derivatives. We sincerely invite your guidance, thank you!

**Comment by weili101** [comment]
Thanks for your interest in this work. Those modifications are for the purpose of rescaling the input coordinates within [0, 1] or [-1, 1].
Suppose that the true coordinates x', y' are in the range  [0, a] and [0, b], the actual input coordinates will be x=x'/a and y=y'/b within range [0, 1]. The same was done for the outputs u=u'/a and v=v'/b (this is actually not necessary).
Therefore, we will have the true derivative du'/dy' = du/dy*a/b.  
Hope that helps!

**Comment by nlqnly** [comment]
Thanks for your answer! We have understood it.
